name: 'Translate Cura plugin'
description: 'Create and update translation of the Cura plugin'
inputs:
  translation_folder: # path for the translation directory usually i18n
    description: 'translation folder of the Cura plugin'
    required: true
    default: 'i18n'
  translation_name: # name of the translation template and locale files (will be used to include translation)
    description: 'translation template and locale files name'
    required: true
  plugin_name: # will be dispayed in the translation files header
    description: 'plugin name'
    required: true
outputs:
  template_updated:
    description: ".pot template updated"
    value: ${{ steps.template_updated.outputs.updated }}
  locales_updated:
    description: ".mo file/files updated"
    value: ${{ steps.locale_updated.outputs.updated }}
runs:
  using: "composite"
  steps:
    - uses: ConorMacBride/install-package@v1
      with:
        apt: gettext

    - name: "Ensure translation folder exists"
      run: mkdir -p "${{ inputs.translation_folder }}"
      shell: bash

    - name: "Check template file exists"
      id: template_exist
      run: echo "::set-output name=exists::$([[ -f ${{ inputs.translation_folder }}/${{ inputs.translation_name }}.pot ]] && echo "true")"
      shell: bash

    - name: Hash current .pot messages
      if: ${{ steps.template_exist.outputs.exists }}
      id: hash_before
      run: echo "::set-output name=i18n_hash::$(grep '^msgid' ${{ inputs.translation_folder }}/${{ inputs.translation_name }}.pot | sort | sha1sum)"
      shell: bash

    - name: Update .pot from Python files
      run: xgettext --package-name='${{ inputs.plugin_name }}' -o ${{ inputs.translation_folder }}/${{ inputs.translation_name }}.pot                 --language=python     --from-code=UTF-8 -ki18n:1 -ki18nc:1c,2 -ki18np:1,2 -ki18ncp:1c,2,3 $(find -L . -name \*.py)
      shell: bash

    - name: Update .pot from QML files
      run: xgettext --package-name='${{ inputs.plugin_name }}' -o ${{ inputs.translation_folder }}/${{ inputs.translation_name }}.pot --join-existing --language=javascript --from-code=UTF-8 -ki18n:1 -ki18nc:1c,2 -ki18np:1,2 -ki18ncp:1c,2,3 $(find -L . -name \*.qml)
      shell: bash

    - name: Hash new .pot messages
      id: hash_after
      run: echo "::set-output name=i18n_hash::$(grep '^msgid' ${{ inputs.translation_folder }}/*.pot | sort | sha1sum)"
      shell: bash

    - name: Set output value
      id: template_updated
      run: echo "::set-output name=updated::${{!!int (steps.hash_after.outputs.i18n_hash != steps.hash_before.outputs.i18n_hash)}}"
      shell: bash

    - name: Update .po files
      if: ${{steps.template_updated.outputs.updated}}
      run: find ${{ inputs.translation_folder }} -name ${{ inputs.translation_name }}.po -exec msgmerge --update {} --backup=none ${{ inputs.translation_folder }}/${{ inputs.translation_name }}.pot \;
      shell: bash

    - name: Ensure LC_MESSAGES folder exists
      if: ${{steps.template_updated.outputs.updated}} #добавить условие на изменение .po файлов
      run: find ${{ inputs.translation_folder }} -maxdepth 1 -name '*_*' -exec mkdir -p {}/LC_MESSAGES \;
      shell: bash

    - name: Update .mo files
      id: locale_updated
      if: ${{steps.template_updated.outputs.updated}} #добавить условие на изменение .po файлов
      run: |
        find ${{ inputs.translation_folder }} -maxdepth 1 -name '*_*' -exec msgfmt {}/${{ inputs.translation_name }}.po -o {}/LC_MESSAGES/${{ inputs.translation_name }}.mo \;
        echo "::set-output name=updated::1"
      shell: bash